DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS character;
DROP TABLE IF EXISTS characters;
DROP TABLE IF EXISTS character_items;
DROP TABLE IF EXISTS character_skills;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS skills;