
CREATE TABLE IF NOT EXISTS public.characters_items(
    FOREIGN KEY item_id REFERENCES items(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY character_id REFERENCES characters(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);